const positions = [
  "Analityk internetowy",
  "Copywriter",
  "Dziennikarz",
  "Fizjoterapeuta",
  "Grafik komputerowy",
  "Kasjer",
  "Kierowca",
  "Korektor tekstu",
  "Magazynier",
  "Ochroniarz",
  "Operator wprowadzania danych",
  "Pracownik administracyjno-biurowy",
  "Pracownik call center",
  "Pracownik ds. obsługi klienta",
  "Pracownik obsługi sklepu internetowego",
  "Pracownik produkcji",
  "Pracownik sprzątający",
  "Programista",
  "Przepisywanie tekstów",
  "Specjalista ds. e-marketingu",
  "Specjalista ds. kadr i płac",
  "Specjalista ds. księgowości",
  "Specjalista ds. rekrutacji",
  "Specjalista IT",
  "Specjalista social media",
  "Sprzedawca",
  "Tłumacz",
  "Transkrypcja nagrań",
  " Web Developer",
];

export default positions;
